# Numpy Array & Opearations

#### Numpy is numerical Python. It is a powerful library used for numerical computating, mathematical operations, data-analysis, and working with multidimensional arrays.

In [2]:
import numpy as np

In [8]:
arr = np.array([10, 20, 30, 40, 50])
print("arr", arr)

arr [10 20 30 40 50]


### 2D Array

In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3D Array

In [10]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Special Array Creation

In [14]:
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Ones

In [15]:
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


### Identity Matrix

In [16]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Range

In [17]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


### Indexing in Numpy

##### indexing is used to access a specific element from an array.

### 1D Array

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])

10
50


### 2D Array

In [4]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr[0][0])
print(arr[1][1])

1
5


### 3D Array

In [5]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr[0, 0, 0])

1


## Slicing in Numpy

##### Slicing extracts multiple lelement of an array.

### 1D Slicing

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])
print(arr[1:])
print(arr[:4])

[20 30 40]
[20 30 40 50]
[10 20 30 40]


### 2D Array Slicing

In [8]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

print(arr[0:2])
print(arr[0:2, 1:3])
print(arr[2: , 2:])


[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[ 9]
 [12]]


### 3D Array Slicing

In [9]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

##### syntax: [depth, row, column]

depth => layer number
row => row number
column => column number

In [10]:
print(arr[0])
print(arr[0,1])
print(arr[0,0])
print(arr[0,0,0])

[[1 2]
 [3 4]]
[3 4]
[1 2]
1


## Mathametical Operation

#### Numpy perform mathametical calculations directly on array.

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(b-a)
print(a*b)
print(b/a)
print(np.sqrt(a))
print(a ** 2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
[1.         1.41421356 1.73205081]
[1 4 9]
