# Numpy Operation in Python with Jupyter NoteBook

import numpy

In [1]:
import numpy as np

### Combining Arrays

##### Horizontal Stacks (hstack)

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.hstack([a,b])
print(result)

[1 2 3 4 5 6]


##### Vertical Stack (vstack)

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.vstack([a,b])
print(result)

[[1 2 3]
 [4 5 6]]


##### Spliting Array

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

result = np.split(arr, 2)
print(result)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


### Search Functions

##### Find Index

In [8]:
arr = np.array([10, 20, 30, 40, 50])

index = np.where(arr == 30)
print(index)

(array([2]),)


##### Search Sorted Position

In [9]:
arr = np.array([10, 20, 30, 40, 50])

position = np.searchsorted(arr, 30, side='right')
print(position)

3


### Sort Function

In [10]:
a = np.array([30, 50, 20, 10, 40])

print(np.sort(a))

[10 20 30 40 50]


### Aggregating & Statstic Function

In [11]:
arr = np.array([10, 20, 30, 40, 50])

print("sum: ", np.sum(arr))
print("mean: ", np.mean(arr))
print("median: ", np.median(arr))
print("max: ", np.max(arr))
print("min: ", np.min(arr))

sum:  150
mean:  30.0
median:  30.0
max:  50
min:  10


### Filter Arrays(Boolean Indexing)

In [12]:
arr = np.array([10, 20, 30, 40, 50])

result = arr[arr < 35]
print(result)

[10 20 30]


##### Multiple Condition

In [13]:
arr = np.array([10, 20, 30, 40, 50])

result = arr[(arr > 20) & (arr < 50)]
print(result)

[30 40]


### Masking Array

In [14]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 35
print(mask)

filtered = arr[mask]
print(filtered)

[False False False  True  True]
[40 50]


### Reshaping Array

##### convert array dimension without changing data.

#### 1D to 3D

In [15]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

result = arr.reshape(2, 2, 2)
print(result)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


#### 1D to 2D

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

result = arr.reshape(2, 4)
print(result)

[[10 20 30 40]
 [50 60 70 80]]


### Array BroadCasting

In [17]:
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
